steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/php-fpm:$_VERSION-$BRANCH_NAME$TAG_NAME', '-f', '$_VERSION/Dockerfile', '.' ]

# slack deployment status
- name: 'gcr.io/cloud-builders/curl'
  args:
      [
          '-X',
          'POST',
          '-H',
          'Content-type: application/json',
          '--data',
          '{"text":"${_IMAGE} build completed!"}',
          '${_WEBHOOK_URL}',
      ]

# extend timeout to 20 min
timeout: 1200s

# store artifact
images: ['gcr.io/$PROJECT_ID/$_IMAGE:$BRANCH_NAME$TAG_NAME']

# arguments
substitutions:
  _VERSION: php_version # PHP runtime version
  _WEBHOOK_URL: slack_notification_webhook # slack notifications
