steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/php-fpm:7.0-$BRANCH_NAME$TAG_NAME', '-f', '7.0/Dockerfile', '.' ]
  dir: '$BRANCH_NAME$TAG_NAME'

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/php-fpm:7.2-$BRANCH_NAME$TAG_NAME', '-f', '7.2/Dockerfile', '.' ]
  dir: '$BRANCH_NAME$TAG_NAME'

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/php-fpm:7.3-$BRANCH_NAME$TAG_NAME', '-f', '7.3/Dockerfile', '.' ]
  dir: '$BRANCH_NAME$TAG_NAME'

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/php-fpm:7.4-$BRANCH_NAME$TAG_NAME', '-f', '7.4/Dockerfile', '.' ]
  dir: '$BRANCH_NAME$TAG_NAME'

# slack deployment status
- name: 'gcr.io/cloud-builders/curl'
  args:
      [
          '-X',
          'POST',
          '-H',
          'Content-type: application/json',
          '--data',
          '{"text":"${_IMAGE} build completed!"}',
          '${_WEBHOOK_URL}',
      ]

# extend timeout to 20 min
timeout: 1200s

# store artifact
images: ['gcr.io/$PROJECT_ID/$_IMAGE:$BRANCH_NAME$TAG_NAME']
