version: "3"

services:
  php82:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
    hostname: php82
    container_name: php82
    volumes:
      - ./configs:/cfgs
    env_file: .env

  redis:
    image: redis:latest
